//
//  RequestEntity.swift
//  HttpRequest
//
//  Created by Chidume Nnamdi on 06/08/2025.
//

import Foundation
import SwiftData

@Model
final class RequestEntity: Identifiable {
    var id = UUID()
    var method: String;
    var url: String;
    var parameters: [Parameter];
    var body = Body();
    var headers: [Header]
    var tests: String;
    var variables: Array<Variable>;

    var authorization = Authorization();

    var urlProtocol: String;
        
    func appendAutoGeneratedHeaders() {
        self.headers += autoGeneratedHeaders
    }
    
    init(method: String, url: String, parameters: [Parameter], body: Body, headers: [Header], tests: String, variables: Array<Variable>,  authorization: Authorization, urlProtocol: String) {
        self.method = method
        self.urlProtocol = urlProtocol
        self.url = url
        self.parameters = parameters
        self.body = body
        self.headers = headers
        self.authorization = authorization
        self.tests = tests
        self.variables = variables
        
        self.appendAutoGeneratedHeaders()
    }
    
    init(parameters: [Parameter]) {
        self.parameters = parameters
        self.method = ""
        self.urlProtocol = ""
        self.url = ""
        self.body = Body()
        self.headers = []
        self.tests = ""
        self.variables = []
        self.authorization = Authorization()
        
        self.appendAutoGeneratedHeaders()

    }
    
    init() {
        self.method = ""
        self.urlProtocol = ""
        self.url = ""
        self.parameters = []
        self.body = Body()
        self.headers = []
        self.authorization = Authorization()
        self.tests = ""
        self.variables = []

        self.appendAutoGeneratedHeaders()

    }
    
}
